
export const SUBJECT_ABBREVIATIONS: { [key: string]: string } = {
    'Computer Architecture Organization': 'CAO',
    'Data Structures': 'DS',
    'Basics of Python Programming': 'BPP',
    'Microcontroller & Interfacing': 'MI',
    'Fundamentals of Economics & Management': 'FOME',
    'Computer Workshop': 'CWS',
    'IoT Architecture and Protocol': 'IOT Arch',
    'Database Management System': 'DBMS',
    'Operating System': 'OS',
    'Geographical Information System': 'GIS',
    'Mathematical Foundation for Data Analysis': 'MFDA',
    'Fog Computing': 'FOG',
    'Theory of Computation and Formal Systems': 'TFCS',
    'Design and Analysis of Algorithms': 'DAA',
    'Neural Networks and Fuzzy Logic': 'NNFL',
    'Ad-hoc Wireless Network': 'AWN',
    'Software Engineering': 'SE',
    'Sensor-based IoT and Data Processing': 'IOT DP',
    'Cloud Computing': 'CC',
    'Fuzzy and Evolutionary Computing': 'FEC',
    'Internet of Things': 'IOT',
    'Blockchain Technology': 'Blockchain',
    'Open Source Computing': 'OSC',
    'Discrete Mathematics and Graph Theory': 'DMPT',
    'Web Technology': 'WT',
    'Communicative Logic': 'CL',
    'Software Engineering': 'FSE',
    'Augmented Reality and Virtual Reality': 'AR-VR',
    'Computer Vision': 'CV',
    'Information System & Forensics': 'ISF',
    'Introduction to Cryptography and Protocol': 'ICP',
    'Modeling and Simulation': 'MS',
    'Statistical Data Analysis': 'SDS',
    'Earth Science & Project Management': 'ESPM',
    'Linear Algebra': 'LA',
    'Big Data Science': 'BDS',
    'Artificial Intelligence': 'AI',
    'Foundation of Machine Learning': 'FML',
    'Cyber Law and Ethics': 'CLE',
    'Compiler Construction': 'CC',
    'Object-Oriented Analysis and Design': 'OOAD',
    'Distributed Systems': 'DS',
    'Cyber Security': 'Cyber Sec',
    'Software Defined Networking and Network Function Virtualization': 'SND & NFV',
    'Big Data Homomorphic Cryptography': 'BDH',
    'Deep Learning': 'DL',
    'Social Network and Data Analysis': 'SNDA',
    'Data Warehousing': 'DW',
    'Data Security': 'D.SEC',
    'Optimization Technique': 'OT',
    'Distributed System': 'Dis Sy',
    'Cryptography': 'CT',
};
