
import type { Lecturer, ScheduleEntry, TimetableData } from './types';

export const LECTURERS: Lecturer[] = [
    { id: 'lec1', name: 'RSB' },
    { id: 'lec2', name: 'Hrushikesh P' },
    { id: 'lec3', name: 'GMD' },
    { id: 'lec4', name: 'Radhika' },
    { id: 'lec5', name: 'CSS' },
    { id: 'lec6', name: 'Sharayu S' },
    { id: 'lec7', name: 'Prachi Gawande' },
    { id: 'lec8', name: 'SSS' },
    { id: 'lec9', name: 'AG' },
    { id: 'lec10', name: 'PVB' },
    { id: 'lec11', name: 'SAS' },
    { id: 'lec12', name: 'RinaP' },
    { id: 'lec13', name: 'Nirmik' },
    { id: 'lec14', name: 'Radhika Tekade' },
];

const cseIotSchedule: ScheduleEntry[] = [
  // Monday
  {
    id: 'c1',
    subject: 'LAB: DBMS / OS',
    lecturer: 'RSB, Hrushikesh P, GMD, Radhika',
    room: 'IOT Lab 1,2 / IOT Lab 3,4',
    day: 'Monday',
    time: '10:00 AM',
    type: 'Practical',
    duration: 2,
    batches: ['A1','A2','A3','A4'],
    color: 'hsl(var(--chart-1))',
  },
  {
    id: 'c2',
    subject: 'PE-I:GIS / MFDA',
    lecturer: 'CSS / Sharayu S',
    room: 'ET-316 / ET-308',
    day: 'Monday',
    time: '12:00 PM',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-2))',
  },
  {
    id: 'c3',
    subject: 'MDM:FOG',
    lecturer: 'Prachi Gawande',
    room: 'ET-316',
    day: 'Monday',
    time: '2:00 PM',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-3))',
  },
  {
    id: 'c4',
    subject: 'TFCS',
    lecturer: 'SSS',
    room: 'ET-316',
    day: 'Monday',
    time: '3:00 PM',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-5))',
  },
  // Tuesday
  {
    id: 'c5',
    subject: 'DBMS',
    lecturer: 'RSB',
    room: 'ET-316',
    day: 'Tuesday',
    time: '10:00 AM',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-1))',
  },
  {
    id: 'c6',
    subject: 'OS',
    lecturer: 'GMD',
    room: 'ET-316',
    day: 'Tuesday',
    time: '11:00 AM',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-4))',
  },
  {
    id: 'c7',
    subject: 'PE-I:GIS / MFDA',
    lecturer: 'CSS / Sharayu S',
    room: 'ET-316 / ET-308',
    day: 'Tuesday',
    time: '12:00 PM',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-2))',
  },
  {
    id: 'c8',
    subject: 'MDM:FOG',
    lecturer: 'Prachi Gawande',
    room: 'ET-316',
    day: 'Tuesday',
    time: '2:00 PM',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-3))',
  },
  {
    id: 'c9',
    subject: 'PE I: LAB: GIS/MFDA',
    lecturer: 'CSS, Radhika / Sharayu S, AG',
    room: 'IOT Lab 3,4 / IOT Lab 1,2',
    day: 'Tuesday',
    time: '3:00 PM',
    type: 'Practical',
    duration: 2,
    batches: ['A1','A2'],
    color: 'hsl(var(--chart-2))',
  },
  // Wednesday
  {
    id: 'c10',
    subject: 'OE:3 Arthashashtra',
    lecturer: 'PVB',
    room: 'ET-316',
    day: 'Wednesday',
    time: '10:00 AM',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-1))',
  },
  {
    id: 'c11',
    subject: 'DAA',
    lecturer: 'SAS',
    room: 'ET-316',
    day: 'Wednesday',
    time: '11:00 AM',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-3))',
  },
  {
    id: 'c12',
    subject: 'DAA',
    lecturer: 'SAS',
    room: 'ET-316',
    day: 'Wednesday',
    time: '12:00 PM',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-3))',
  },
  {
    id: 'c13',
    subject: 'MDM:FOG',
    lecturer: 'Prachi Gawande',
    room: 'ET-316',
    day: 'Wednesday',
    time: '2:00 PM',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-2))',
  },
  {
    id: 'c14',
    subject: 'LAB: OS/DAA',
    lecturer: 'GMD, Hrushikesh P, SAS, RinaP',
    room: 'IOT Lab 3,4 / IOT Lab 1,2',
    day: 'Wednesday',
    time: '3:00 PM',
    type: 'Practical',
    duration: 2,
    batches: ['A1','A2','A3','A4'],
    color: 'hsl(var(--chart-5))',
  },
  // Thursday
  {
    id: 'c15',
    subject: 'OE:3 Arthashashtra',
    lecturer: 'PVB',
    room: 'ET-316',
    day: 'Thursday',
    time: '9:00 AM',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-1))',
  },
  {
    id: 'c16',
    subject: 'DBMS',
    lecturer: 'RSB',
    room: 'ET-316',
    day: 'Thursday',
    time: '10:00 AM',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-2))',
  },
  {
    id: 'c17',
    subject: 'LAB: DBMS/DAA',
    lecturer: 'RSB, RinaP / SAS, Nirmik',
    room: 'IOT Lab 1,2 / IOT Lab 3,4',
    day: 'Thursday',
    time: '11:00 AM',
    type: 'Practical',
    duration: 2,
    batches: ['A3','A4','A1','A2'],
    color: 'hsl(var(--chart-5))',
  },
  {
    id: 'c18',
    subject: 'OS',
    lecturer: 'GMD',
    room: 'ET-316',
    day: 'Thursday',
    time: '2:00 PM',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-4))',
  },
  {
    id: 'c19',
    subject: 'HELP DESK',
    lecturer: '',
    room: '',
    day: 'Thursday',
    time: '3:00 PM',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--card))',
  },
  {
    id: 'c20',
    subject: 'SPORTS',
    lecturer: '',
    room: '',
    day: 'Thursday',
    time: '4:00 PM',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-2))',
  },
  // Friday
  {
    id: 'c21',
    subject: 'OE:3 Arthashashtra',
    lecturer: 'PVB',
    room: 'ET-316',
    day: 'Friday',
    time: '9:00 AM',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-1))',
  },
  {
    id: 'c22',
    subject: 'OS',
    lecturer: 'GMD',
    room: 'ET-316',
    day: 'Friday',
    time: '10:00 AM',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-4))',
  },
  {
    id: 'c23',
    subject: 'TFCS',
    lecturer: 'SSS',
    room: 'ET-316',
    day: 'Friday',
    time: '11:00 AM',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-5))',
  },
  {
    id: 'c24',
    subject: 'DBMS',
    lecturer: 'RSB',
    room: 'ET-316',
    day: 'Friday',
    time: '2:00 PM',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-2))',
  },
  {
    id: 'c25',
    subject: 'DAA',
    lecturer: 'SAS',
    room: 'ET-316',
    day: 'Friday',
    time: '3:00 PM',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-3))',
  },
  {
    id: 'c26',
    subject: 'LIBRARY',
    lecturer: 'RADHIKA Tekade',
    room: '',
    day: 'Friday',
    time: '4:00 PM',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-2))',
  },
  {
    id: 'c27',
    subject: 'SPORTS',
    lecturer: '',
    room: '',
    day: 'Friday',
    time: '5:00 PM',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-2))',
  },
];


export const MASTER_SCHEDULE: TimetableData[] = [
    {
        id: 'tt1',
        name: 'CSE(IOT) - Semester 5',
        schedule: cseIotSchedule
    }
];
