
import type { Lecturer, ScheduleEntry, TimetableData } from './types';

export const LECTURERS: Lecturer[] = [
    { id: 'lec1', name: 'Roshan S. Bhanuse' },
    { id: 'lec2', name: 'Hrushikesh P' },
    { id: 'lec3', name: 'Dr. Gauri M. Dhopavkar' },
    { id: 'lec4', name: 'Radhika' },
    { id: 'lec5', name: 'Charvi S. Suri' },
    { id: 'lec6', name: 'Sharayu Sangekar' },
    { id: 'lec7', name: 'Prachi Gawande' },
    { id: 'lec8', name: 'Dr. S. S. Sherekar' },
    { id: 'lec9', name: 'Gousia Ahmed' },
    { id: 'lec10', name: 'P.V.Barekar' },
    { id: 'lec11', name: 'Dr. S. A. Shirsat' },
    { id: 'lec12', name: 'Rina Parteki' },
    { id: 'lec13', name: 'Nirmik' },
    { id: 'lec14', name: 'Radhika Tekade' },
    { id: 'lec15', name: 'Lata R. Tembhare' },
    { id: 'lec16', name: 'Harsha Tembhekar' },
    { id: 'lec17', name: 'Priya Kotewar' },
    { id: 'lec18', name: 'Sadaf' },
    { id: 'lec19', name: 'Dr. Rathkanthiwar' },
    { id: 'lec20', name: 'S. Khan' },
    { id: 'lec21', name: 'Kirti S.' },
    { id: 'lec22', name: 'Dr. A. B. Thatere' },
    { id: 'lec23', name: 'Prachi A. Bainalwar' },
    { id: 'lec24', name: 'Nilesh U. Sambhe' },
    { id: 'lec25', name: 'Dr. Prarthana Deshkar' },
    { id: 'lec26', name: 'Dr. Ganesh Yenurkar' },
    { id: 'lec27', name: 'Dr. Sanjay P. Pande' },
    { id: 'lec28', name: 'S. Saba' },
    { id: 'lec29', name: 'Dr. S. J. Kadarpachi' },
    { id: 'lec30', name: 'Dr. G. M. Vidhale' },
    { id: 'lec31', name: 'S. S. Bhadoria' },
];

const cseIotSem5Schedule: ScheduleEntry[] = [
  // Monday
  {
    id: 'c1',
    subject: 'LAB: DBMS / OS',
    lecturer: 'Roshan S. Bhanuse, Hrushikesh P, Dr. Gauri M. Dhopavkar, Radhika',
    room: 'IOT Lab 1,2 / IOT Lab 3,4',
    day: 'Monday',
    time: '10:00-11:00',
    type: 'Practical',
    duration: 2,
    batches: ['A1','A2','A3','A4'],
    color: 'hsl(var(--chart-1))',
  },
  {
    id: 'c2',
    subject: 'PE-I:GIS / MFDA',
    lecturer: 'Charvi S. Suri / Sharayu Sangekar',
    room: 'ET-316 / ET-308',
    day: 'Monday',
    time: '12:00-1:00',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-2))',
  },
  {
    id: 'c3',
    subject: 'MDM:FOG',
    lecturer: 'Prachi Gawande',
    room: 'ET-316',
    day: 'Monday',
    time: '2:00-3:00',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-3))',
  },
  {
    id: 'c4',
    subject: 'TFCS',
    lecturer: 'Dr. S. S. Sherekar',
    room: 'ET-316',
    day: 'Monday',
    time: '3:00-4:00',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-5))',
  },
  // Tuesday
  {
    id: 'c5',
    subject: 'DBMS',
    lecturer: 'Roshan S. Bhanuse',
    room: 'ET-316',
    day: 'Tuesday',
    time: '10:00-11:00',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-1))',
  },
  {
    id: 'c6',
    subject: 'OS',
    lecturer: 'Dr. Gauri M. Dhopavkar',
    room: 'ET-316',
    day: 'Tuesday',
    time: '11:00-12:00',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-4))',
  },
  {
    id: 'c7',
    subject: 'PE-I:GIS / MFDA',
    lecturer: 'Charvi S. Suri / Sharayu Sangekar',
    room: 'ET-316 / ET-308',
    day: 'Tuesday',
    time: '12:00-1:00',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-2))',
  },
  {
    id: 'c8',
    subject: 'MDM:FOG',
    lecturer: 'Prachi Gawande',
    room: 'ET-316',
    day: 'Tuesday',
    time: '2:00-3:00',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-3))',
  },
  {
    id: 'c9',
    subject: 'PE I: LAB: GIS/MFDA',
    lecturer: 'Charvi S. Suri, Radhika / Sharayu Sangekar, Gousia Ahmed',
    room: 'IOT Lab 3,4 / IOT Lab 1,2',
    day: 'Tuesday',
    time: '3:00-4:00',
    type: 'Practical',
    duration: 2,
    batches: ['A1','A2'],
    color: 'hsl(var(--chart-2))',
  },
  // Wednesday
  {
    id: 'c10',
    subject: 'OE:3 Arthashashtra',
    lecturer: 'P.V.Barekar',
    room: 'ET-316',
    day: 'Wednesday',
    time: '10:00-11:00',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-1))',
  },
  {
    id: 'c11',
    subject: 'DAA',
    lecturer: 'Dr. S. A. Shirsat',
    room: 'ET-316',
    day: 'Wednesday',
    time: '11:00-12:00',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-3))',
  },
  {
    id: 'c12',
    subject: 'DAA',
    lecturer: 'Dr. S. A. Shirsat',
    room: 'ET-316',
    day: 'Wednesday',
    time: '12:00-1:00',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-3))',
  },
  {
    id: 'c13',
    subject: 'MDM:FOG',
    lecturer: 'Prachi Gawande',
    room: 'ET-316',
    day: 'Wednesday',
    time: '2:00-3:00',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-2))',
  },
  {
    id: 'c14',
    subject: 'LAB: OS/DAA',
    lecturer: 'Dr. Gauri M. Dhopavkar, Hrushikesh P, Dr. S. A. Shirsat, Rina Parteki',
    room: 'IOT Lab 3,4 / IOT Lab 1,2',
    day: 'Wednesday',
    time: '3:00-4:00',
    type: 'Practical',
    duration: 2,
    batches: ['A1','A2','A3','A4'],
    color: 'hsl(var(--chart-5))',
  },
  // Thursday
  {
    id: 'c15',
    subject: 'OE:3 Arthashashtra',
    lecturer: 'P.V.Barekar',
    room: 'ET-316',
    day: 'Thursday',
    time: '09:00-10:00',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-1))',
  },
  {
    id: 'c16',
    subject: 'DBMS',
    lecturer: 'Roshan S. Bhanuse',
    room: 'ET-316',
    day: 'Thursday',
    time: '10:00-11:00',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-2))',
  },
  {
    id: 'c17',
    subject: 'LAB: DBMS/DAA',
    lecturer: 'Roshan S. Bhanuse, Rina Parteki / Dr. S. A. Shirsat, Nirmik',
    room: 'IOT Lab 1,2 / IOT Lab 3,4',
    day: 'Thursday',
    time: '11:00-12:00',
    type: 'Practical',
    duration: 2,
    batches: ['A3','A4','A1','A2'],
    color: 'hsl(var(--chart-5))',
  },
  {
    id: 'c18',
    subject: 'OS',
    lecturer: 'Dr. Gauri M. Dhopavkar',
    room: 'ET-316',
    day: 'Thursday',
    time: '2:00-3:00',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-4))',
  },
  {
    id: 'c19',
    subject: 'HELP DESK',
    lecturer: '',
    room: '',
    day: 'Thursday',
    time: '3:00-4:00',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--card))',
  },
  {
    id: 'c20',
    subject: 'SPORTS',
    lecturer: '',
    room: '',
    day: 'Thursday',
    time: '4:00-5:00',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-2))',
  },
  // Friday
  {
    id: 'c21',
    subject: 'OE:3 Arthashashtra',
    lecturer: 'P.V.Barekar',
    room: 'ET-316',
    day: 'Friday',
    time: '09:00-10:00',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-1))',
  },
  {
    id: 'c22',
    subject: 'OS',
    lecturer: 'Dr. Gauri M. Dhopavkar',
    room: 'ET-316',
    day: 'Friday',
    time: '10:00-11:00',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-4))',
  },
  {
    id: 'c23',
    subject: 'TFCS',
    lecturer: 'Dr. S. S. Sherekar',
    room: 'ET-316',
    day: 'Friday',
    time: '11:00-12:00',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-5))',
  },
  {
    id: 'c24',
    subject: 'DBMS',
    lecturer: 'Roshan S. Bhanuse',
    room: 'ET-316',
    day: 'Friday',
    time: '2:00-3:00',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-2))',
  },
  {
    id: 'c25',
    subject: 'DAA',
    lecturer: 'Dr. S. A. Shirsat',
    room: 'ET-316',
    day: 'Friday',
    time: '3:00-4:00',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-3))',
  },
  {
    id: 'c26',
    subject: 'LIBRARY',
    lecturer: 'Radhika Tekade',
    room: '',
    day: 'Friday',
    time: '4:00-5:00',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-2))',
  },
  {
    id: 'c27',
    subject: 'SPORTS',
    lecturer: '',
    room: '',
    day: 'Friday',
    time: '4:00-5:00',
    type: 'Lecture',
    duration: 1,
    color: 'hsl(var(--chart-2))',
  },
];

const cseIotSem3Schedule: ScheduleEntry[] = [
  // Monday
  { id: 's3c1', subject: 'OE:1', lecturer: '', room: 'ET-308', day: 'Monday', time: '10:00-11:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-2))' },
  { id: 's3c2', subject: 'CAO', lecturer: 'Harsha Tembhekar', room: 'ET-308', day: 'Monday', time: '11:00-12:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-3))' },
  { id: 's3c3', subject: 'DS', lecturer: 'Lata R. Tembhare', room: 'ET-308', day: 'Monday', time: '1:00-2:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-4))' },
  { id: 's3c4', subject: 'LIBRARY', lecturer: 'Lata R. Tembhare', room: '', day: 'Monday', time: '2:00-3:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-4))' },
  { id: 's3c5', subject: 'LAB: DS/ CWS', lecturer: 'Lata R. Tembhare, Rina Parteki/Harsha Tembhekar, Sharayu Sangekar', room: 'IOT Lab 3,4/IOT Lab 1,2', day: 'Monday', time: '3:00-4:00', type: 'Practical', duration: 2, batches: ['A1','A2','A3','A4'], color: 'hsl(var(--chart-1))' },
  
  // Tuesday
  { id: 's3c6', subject: 'OE:1', lecturer: '', room: 'ET-308', day: 'Tuesday', time: '10:00-11:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-2))' },
  { id: 's3c7', subject: 'BPP', lecturer: 'Rina Parteki', room: 'ET-308', day: 'Tuesday', time: '11:00-12:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-5))' },
  { id: 's3c8', subject: 'DS', lecturer: 'Lata R. Tembhare', room: 'ET-308', day: 'Tuesday', time: '1:00-2:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-4))' },
  { id: 's3c9', subject: 'MI', lecturer: 'S. Khan', room: 'ET-308', day: 'Tuesday', time: '2:00-3:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-3))' },
  { id: 's3c10', subject: 'SPORTS', lecturer: '', room: '', day: 'Tuesday', time: '3:00-4:00', type: 'Lecture', duration: 2, color: 'hsl(var(--chart-1))' },

  // Wednesday
  { id: 's3c11', subject: 'CAO', lecturer: 'Harsha Tembhekar', room: 'ET-308', day: 'Wednesday', time: '10:00-11:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-3))' },
  { id: 's3c12', subject: 'MI', lecturer: 'S. Khan', room: 'ET-308', day: 'Wednesday', time: '11:00-12:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-3))' },
  { id: 's3c13', subject: 'DS', lecturer: 'Lata R. Tembhare', room: 'ET-308', day: 'Wednesday', time: '1:00-2:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-4))' },
  { id: 's3c14', subject: 'BPP', lecturer: 'Rina Parteki', room: 'ET-308', day: 'Wednesday', time: '2:00-3:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-5))' },
  { id: 's3c15', subject: 'FOME', lecturer: 'Dr. G. M. Vidhale', room: 'ET-308', day: 'Wednesday', time: '3:00-4:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-2))' },
  { id: 's3c16', subject: 'HELP DESK', lecturer: '', room: '', day: 'Wednesday', time: '4:00-5:00', type: 'Lecture', duration: 1, color: 'hsl(var(--card))' },

  // Thursday
  { id: 's3c17', subject: 'BPP', lecturer: 'Rina Parteki', room: 'ET-308', day: 'Thursday', time: '10:00-11:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-5))' },
  { id: 's3c18', subject: 'FOME', lecturer: 'Dr. G. M. Vidhale', room: 'ET-308', day: 'Thursday', time: '11:00-12:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-2))' },
  { id: 's3c19', subject: 'CAO', lecturer: 'Harsha Tembhekar', room: 'ET-308', day: 'Thursday', time: '1:00-2:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-3))' },
  { id: 's3c20', subject: 'MDM 1: IOT Arch. Pro.', lecturer: 'Priya Kotewar', room: 'ET-308', day: 'Thursday', time: '2:00-3:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-3))' },
  { id: 's3c21', subject: 'LAB: DS/ CWS', lecturer: 'Lata R. Tembhare, Charvi S. Suri/Harsha Tembhekar, Sadaf', room: 'IOT Lab 3,4/IOT Lab 1,2', day: 'Thursday', time: '3:00-4:00', type: 'Practical', duration: 2, batches: ['A3','A4','A1','A2'], color: 'hsl(var(--chart-1))' },
  
  // Friday
  { id: 's3c22', subject: 'MI', lecturer: 'S. Khan', room: 'ET-308', day: 'Friday', time: '10:00-11:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-3))' },
  { id: 's3c23', subject: 'CAO', lecturer: 'Harsha Tembhekar', room: 'ET-308', day: 'Friday', time: '11:00-12:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-3))' },
  { id: 's3c24', subject: 'DS', lecturer: 'Lata R. Tembhare', room: 'ET-308', day: 'Friday', time: '1:00-2:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-4))' },
  { id: 's3c25', subject: 'MDM 1: IOT Arch. Pro.', lecturer: 'Priya Kotewar', room: 'ET-308', day: 'Friday', time: '2:00-3:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-3))' },
  { id: 's3c26', subject: 'LAB: MI', lecturer: 'Dr. Rathkanthiwar, S. Khan, , Kirti S., Dr. A. B. Thatere', room: 'IOT Lab 1,2/IOT Lab 3,4', day: 'Friday', time: '3:00-4:00', type: 'Practical', duration: 2, batches: ['A1','A2','A3','A4'], color: 'hsl(var(--chart-5))' },
];

const cseIotSem7Schedule: ScheduleEntry[] = [
  // Monday
  { id: 's7c1', subject: 'PE-V: Blockchain/OSC', lecturer: 'Prachi A. Bainalwar/Gousia Ahmed', room: 'EL-204/EL 203', day: 'Monday', time: '11:00-12:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-1))' },
  { id: 's7c2', subject: 'SE', lecturer: 'Nilesh U. Sambhe', room: 'EL 302', day: 'Monday', time: '12:00-1:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-2))' },
  { id: 's7c3', subject: 'PE-IV: SPI/DAI', lecturer: 'Harsha Tembhekar/Dr. Prarthana Deshkar', room: 'EL 302/EL 102', day: 'Monday', time: '1:00-2:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-3))' },
  { id: 's7c4', subject: 'CC', lecturer: 'Dr. Ganesh Yenurkar', room: 'ET 308', day: 'Monday', time: '3:00-4:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-4))' },
  { id: 's7c5', subject: 'IOT DP', lecturer: 'Dr. Sanjay P. Pande', room: 'ET 308', day: 'Monday', time: '4:00-5:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-5))' },

  // Tuesday
  { id: 's7c6', subject: 'LAB: SE/CC', lecturer: 'Nilesh U. Sambhe, Dr. Prarthana Deshkar/Dr. Ganesh Yenurkar, Gousia Ahmed', room: 'IOT Lab 1,2/IOT Lab 3,4', day: 'Tuesday', time: '10:00-11:00', type: 'Practical', duration: 2, batches: ['A1,A2', 'A3,A4'], color: 'hsl(var(--chart-2))' },
  { id: 's7c7', subject: 'PE-IV: SPI/DAI', lecturer: 'Harsha Tembhekar/Dr. Prarthana Deshkar', room: 'EL 302/EL 102', day: 'Tuesday', time: '1:00-2:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-3))' },
  { id: 's7c8', subject: 'LIBRARY', lecturer: 'Gousia Ahmed', room: '', day: 'Tuesday', time: '2:00-3:00', type: 'Lecture', duration: 1, color: 'hsl(var(--card))' },
  { id: 's7c9', subject: 'CC', lecturer: 'Dr. Ganesh Yenurkar', room: 'EL 103', day: 'Tuesday', time: '3:00-4:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-4))' },
  { id: 's7c10', subject: 'IOT DP', lecturer: 'Dr. Sanjay P. Pande', room: 'EL 103', day: 'Tuesday', time: '4:00-5:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-5))' },
  
  // Wednesday
  { id: 's7c11', subject: 'PE III: LAB: IOT/FEC', lecturer: 'Nirmik/Prachi Gawande, Dr. S. J. Kadarpachi', room: 'IOT Lab 1,2/IOT Lab 3,4', day: 'Wednesday', time: '10:00-11:00', type: 'Practical', duration: 2, batches: ['A1,A2'], color: 'hsl(var(--chart-1))' },
  { id: 's7c12', subject: 'S. Saba', lecturer: 'S. Saba', room: '', day: 'Wednesday', time: '11:00-12:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-2))' },
  { id: 's7c13', subject: 'PE-III: IOT/FEC', lecturer: 'S. Saba/Prachi Gawande', room: 'EL-204/EL102', day: 'Wednesday', time: '1:00-2:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-1))' },
  { id: 's7c14', subject: 'Project', lecturer: '', room: '', day: 'Wednesday', time: '2:00-3:00', type: 'Lecture', duration: 3, color: 'hsl(var(--muted))' },

  // Thursday
  { id: 's7c15', subject: 'SE', lecturer: 'Nilesh U. Sambhe', room: 'EL 211', day: 'Thursday', time: '10:00-11:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-2))' },
  { id: 's7c16', subject: 'PE-IV: SPI/DAI', lecturer: 'Harsha Tembhekar/Dr. Prarthana Deshkar', room: 'ET316/EL 211', day: 'Thursday', time: '11:00-12:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-3))' },
  { id: 's7c17', subject: 'PE-V: Blockchain/OSC', lecturer: 'Prachi A. Bainalwar/Gousia Ahmed', room: 'AIDS Lab 2/AIDS Lab 1', day: 'Thursday', time: '2:00-3:00', type: 'Practical', duration: 2, color: 'hsl(var(--chart-1))' },
  { id: 's7c18', subject: 'IOT DP', lecturer: 'Dr. Sanjay P. Pande', room: 'EL 211', day: 'Thursday', time: '4:00-5:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-5))' },
  { id: 's7c19', subject: 'HELP DESK', lecturer: '', room: '', day: 'Thursday', time: '4:00-5:00', type: 'Lecture', duration: 1, color: 'hsl(var(--card))' },

  // Friday
  { id: 's7c20', subject: 'LAB: SE/CC', lecturer: 'Nilesh U. Sambhe, Dr. G. M. Vidhale/Dr. Ganesh Yenurkar, S. S. Bhadoria', room: 'IOT Lab 1,2/IOT Lab 3,4', day: 'Friday', time: '10:00-11:00', type: 'Practical', duration: 2, batches: ['A3,A4', 'A1,A2'], color: 'hsl(var(--chart-2))' },
  { id: 's7c21', subject: 'PE-III: IOT/FEC', lecturer: 'S. Saba/Prachi Gawande', room: 'ET 308/ET 316', day: 'Friday', time: '12:00-1:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-1))' },
  { id: 's7c22', subject: 'PE-V: Blockchain/OSC', lecturer: 'Prachi A. Bainalwar/Gousia Ahmed', room: 'AIDS Lab 2/EL-204', day: 'Friday', time: '2:00-3:00', type: 'Practical', duration: 2, color: 'hsl(var(--chart-1))' },
  { id: 's7c23', subject: 'SE', lecturer: 'Nilesh U. Sambhe', room: 'EL 211', day: 'Friday', time: '4:00-5:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-2))' },
  { id: 's7c24', subject: 'CC', lecturer: 'Dr. Ganesh Yenurkar', room: 'EL 102', day: 'Friday', time: '4:00-5:00', type: 'Lecture', duration: 1, color: 'hsl(var(--chart-4))' },

];


export const MASTER_SCHEDULE: TimetableData[] = [
    {
        id: 'tt1',
        name: 'CSE(IOT) - Semester 5',
        schedule: cseIotSem5Schedule
    },
    {
        id: 'tt2',
        name: 'CSE(IOT) - Semester 3',
        schedule: cseIotSem3Schedule
    },
    {
        id: 'tt3',
        name: 'CSE(IOT) - Semester 7',
        schedule: cseIotSem7Schedule
    }
];
